Update post-installation

diff --git a/post-installation b/post-installation
--- a/post-installation
+++ b/post-installation
@@ -34,45 +34,43 @@ source src/setup/system_setup.sh
 function install_aur_helper() {
     local git_repo
 
-    # Check if both yay and paru are not installed
-    if ! command -v yay &> /dev/null && ! command -v paru &> /dev/null; then
-        echo "Choisissez un AUR helper (yay/paru):"
-        read -p "Entrez votre choix: " AUR_HELPER
+    # Always prompt the user for AUR helper choice
+    echo "Choisissez un AUR helper (yay/paru):"
+    read -p "Entrez votre choix: " AUR_HELPER 
+    AUR_HELPER=$(echo "$AUR_HELPER" | tr '[:upper:]' '[:lower:]')  # Convert input to lowercase
+
+    while [[ ! " yay paru " =~ " ${AUR_HELPER} " ]]; do
+        echo "Choix invalide."
+        read -p "Entrez yay ou paru: " AUR_HELPER
         AUR_HELPER=$(echo "$AUR_HELPER" | tr '[:upper:]' '[:lower:]')  # Convert input to lowercase
+    done
 
-        while [[ ! " yay paru " =~ " ${AUR_HELPER} " ]]; do
-            echo "Choix invalide."
-            read -p "Entrez yay ou paru: " AUR_HELPER
-            AUR_HELPER=$(echo "$AUR_HELPER" | tr '[:upper:]' '[:lower:]')  # Convert input to lowercase
-        done
+    case "$AUR_HELPER" in
+        yay)
+            git_repo="https://aur.archlinux.org/yay-bin.git"
+            ;;
+        paru)
+            git_repo="https://aur.archlinux.org/paru-bin.git"
+            ;;
+    esac
 
-        case "$AUR_HELPER" in
-            yay)
-                git_repo="https://aur.archlinux.org/yay-bin.git"
-                ;;
-            paru)
-                git_repo="https://aur.archlinux.org/paru-bin.git"
-                ;;
-        esac
+    echo "Installation de $AUR_HELPER."
+    sudo pacman -S --noconfirm git >> /dev/null 2>&1
+    git clone $git_repo >> /dev/null 2>&1
+    cd "${AUR_HELPER}-bin" || exit
+    echo "|- Compilation de $AUR_HELPER."
+    makepkg -si --noconfirm >> /dev/null 2>&1
+    cd .. || exit
+    rm -rf "${AUR_HELPER}-bin" >> /dev/null 2>&1
 
-        echo "Installation de $AUR_HELPER."
-        sudo pacman -S --noconfirm git >> /dev/null 2>&1
-        git clone $git_repo >> /dev/null 2>&1
-        cd "${AUR_HELPER}-bin" || exit
-        echo "|- Compilation de $AUR_HELPER."
-        makepkg -si --noconfirm >> /dev/null 2>&1
-        cd .. || exit
-        rm -rf "${AUR_HELPER}-bin" >> /dev/null 2>&1
-
-        if [ "$AUR_HELPER" == "yay" ]; then
-            yay -Y --gendb
-            yay -Y --devel --save
-        elif [ "$AUR_HELPER" == "paru" ]; then
-            paru --gendb
-        fi
-
-        echo "--------------------------------------------------"
+    if [ "$AUR_HELPER" == "yay" ]; then
+        yay -Y --gendb
+        yay -Y --devel --save
+    elif [ "$AUR_HELPER" == "paru" ]; then
+        paru --gendb
     fi
+
+    echo "--------------------------------------------------"
 }
 
 # This function displays a welcome message to the user and prompts them to continue with the script or cancel it.
